swagger: "2.0"
info:
  description: "API for managing business transactions"
  version: "1.0.0"
  title: "Interlinked Open API"
  contact:
    email: "andrey.orlov@spherity.com"
host: "85cfuud886.execute-api.eu-central-1.amazonaws.com"
basePath: "/Prod"
tags:
- name: "Business Transactions"
  description: "Everything about business transactions"
schemes:
- "https"
paths:
  /biz-txs:
    post:
      tags:
      - "Business Transactions"
      summary: "Create new business transactions"
      description: ""
      operationId: "createBizTxs"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Biz transactions that needs to be saved"
        required: true
        schema:
          $ref: "#/definitions/BizTxs"
      responses:
        200:
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/CreateBizTxsResponse"
        403:
          description: "Access token is invalid."
          schema:
            $ref: "#/definitions/ApiError"
        422:
          description: "Base claim with Sender and Recipient as payload items was not found"
          schema:
            $ref: "#/definitions/ApiError"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ApiError"
    get:
      tags:
      - "Business Transactions"
      summary: "Get business transactions"
      description: ""
      operationId: "getBizTxs"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        required: true
        type: "string"
      - name: "sender"
        in: "query"
        description: "find using sender filter"
        required: false
        type: "string"
      - name: "recipient"
        in: "query"
        description: "find using recipient filter"
        required: false
        type: "string"
      responses:
        200:
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/GetBizTxsResponse"
        403:
          description: "Access token is invalid."
          schema:
            $ref: "#/definitions/ApiError"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ApiError"
    put:
      tags:
      - "Business Transactions"
      summary: "Update business transactions"
      description: ""
      operationId: "updateBizTxs"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Transactions that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/BizTxs"
      responses:
        200:
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/CreateBizTxsResponse"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ApiError"
    delete:
      tags:
      - "Business Transactions"
      summary: "Delete business transactions"
      description: ""
      operationId: "deleteBizTxs"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "header"
        name: "Authorization"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Transactions ids that needs to be deleted"
        required: true
        schema:
          type: "array"
          items:
            type: "string"
      responses:
        200:
          description: "Successfull operation"
        500:
          description: "Server Error"
          schema:
            $ref: "#/definitions/ApiError"
definitions:
  BizTxs:
    type: "array"
    items:
      $ref: "#/definitions/BizTx"
    xml:
      name: "BizTxs"
  BizTx:
    type: "object"
    required:
    - hol
    - claims
    - did
    properties:
      hol:
        type: "string"
      did:
        type: "string"
      exp:
        type: "integer"
      aud:
        type: "string"
      claims:
        type: "array"
        items:
          $ref: "#/definitions/Claim"
    xml:
      name: "BizTx"
  Claim:
    type: "object"
    required:
    - payload
    properties:
      did:
        type: "string"
      exp:
        type: "integer"
      sub:
        type: "string"
      aud:
        type: "string"
      readers:
        type: "array"
        items:
          type: "string"
      payload:
        type: "object"
    xml:
      name: "Claim"
  CreateBizTxsResponse:
    type: "array"
    items:
      $ref: "#/definitions/CreatedBizTx"
  CreatedBizTx:
    allOf:
    - $ref: "#/definitions/BizTx"
    - type: "object"
      properties:
        _id:
          type: "string"
        createdAt:
          type: "integer"
        status:
          type: "string"
        claims:
          type: "array"
          items:
            $ref: "#/definitions/CreatedBizTxClaim"
  CreatedBizTxClaim:
    allOf:
    - $ref: "#/definitions/Claim"
    - type: "object"
      properties:
        _id:
          type: "string"
        signature:
          type: "string"
        data:
          type: "string"
        sub:
          type: "string"
        iat:
          type: "integer"
        exp:
          type: "integer"
        iss:
          type: "string"
        issName:
          type: "string"
        did:
          type: "string"
        payload:
          type: "object"
        algInfo:
          type: "object"
          properties:
            alg:
              type: string
            typ:
              type: string
  GetBizTxsResponse:
    type: "array"
    items:
      $ref: "#/definitions/GetBizTx"
  GetBizTx:
    type: "object"
    properties:
      _id:
        type: "string"
      createdAt:
        type: "integer"
      did:
        type: "string"
      sender:
        type: "string"
      senderDid:
        type: "string"
      senderDidOwner:
        type: "string"
      senderDidName:
        type: "string"
      senderDidOwnerName:
        type: "string"
      recipient:
        type: "string"
      recipientDid:
        type: "string"
      recipientDidOwner:
        type: "string"
      recipientDidName:
        type: "string"
      recipientDidOwnerName:
        type: "string"
  ApiError:
    type: "object"
    properties:
      errorType:
        type: "string"
      errorMessage:
        type: "string"
      innerException:
        type: "object"
externalDocs:
  description: "Spherity website"
  url: "https://spherity.com/"